# Generated by Django 2.1.4 on 2018-12-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0004_blogpost_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='subtitle',
            field=models.CharField(max_length=100, null=True, verbose_name='Subtítulo'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(max_length=30, unique=True),
        ),
    ]
