# Generated by Django 2.1.4 on 2018-12-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0008_auto_20181229_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Subtítulo'),
        ),
    ]
