# Generated by Django 2.1.4 on 2018-12-29 16:01

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0010_auto_20181229_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content_html',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
