# Generated by Django 2.1.4 on 2018-12-30 21:32

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0010_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content_html',
            field=froala_editor.fields.FroalaField(null=True),
        ),
    ]
