# Generated by Django 2.1.4 on 2018-12-30 21:35

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0012_blogpost_content_html'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='content_html',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=froala_editor.fields.FroalaField(null=True, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Imagen en preview'),
        ),
    ]
